"""Миграция

Revision ID: cfa24aef3293
Revises: 
Create Date: 2025-10-07 22:33:29.563849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa24aef3293'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('game_sid', sa.UUID(), nullable=False),
    sa.Column('player_sid', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('is_ship', sa.Boolean(), nullable=True),
    sa.Column('is_hit', sa.Boolean(), nullable=True),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )

    op.create_table('players',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sid'),
    sa.UniqueConstraint('username')
    )

    op.create_table('games',
    sa.Column('player1_sid', sa.UUID(), nullable=False),
    sa.Column('player2_sid', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'active', 'finished', name='gamestatus'), nullable=False),
    sa.Column('winner_sid', sa.UUID(), nullable=True),
    sa.Column('current_turn_sid', sa.UUID(), nullable=True),
    sa.Column('sid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_turn_sid'], ['players.sid'], ),
    sa.ForeignKeyConstraint(['player1_sid'], ['players.sid'], ),
    sa.ForeignKeyConstraint(['player2_sid'], ['players.sid'], ),
    sa.ForeignKeyConstraint(['winner_sid'], ['players.sid'], ),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('boards')
    # ### end Alembic commands ###
